In [1]:
import pandas as pd 
import numpy as np 
from collections import Counter
pd.set_option("display.max_column",100)
pd.set_option("expand_frame_repr",False)

In [2]:
all_data_test=pd.read_csv(r'D:\文件\学习\数据集\天猫用户复购\data_format1\random_2000.csv',index_col=False)

In [3]:
all_data_test.head()

   Unnamed: 0  user_id                                          item_path                                           cat_path                                        seller_path                                         brand_path                                    time_stamp_path                                   action_type_path
0           0        1  181459,779078,779078,452837,543397,504149,5041...  276,276,276,276,276,1023,1023,1023,1023,1252,1...  2245,2245,2245,2245,2245,925,925,925,925,4026,...  4750.0,4750.0,4750.0,4750.0,4750.0,7402.0,7402...  1009,1009,1009,1009,1009,1011,1011,1011,1011,1...  0,0,0,0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,2,2,...
1           1        2  348983,749563,239288,751744,239288,714176,1972...  177,177,602,602,602,1213,602,602,602,1213,1213...  2223,2223,420,420,420,420,420,420,420,420,420,...  3273.0,3273.0,4953.0,4953.0,4953.0,4058.0,4953...  527,527,626,626,626,626,626,626,626,626,626,62...  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,0,0,...
2           2        3  895754,895754,182882,182882,985337,175397,9463...  1505,1505,1271,1271,1271,662,1134,1134,1134,45...  795,795,2123,2123,4925,1102,4461,4461,4461,474...  3608.0,3608.0,4796.0,4796.0,8005.0,1214.0,905....  516,516,627,627,627,727,819,819,820,906,906,90...  2,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...
3           3        4  836727,243874,185489,95474,30073,790055,790055...  612,1577,1505,1505,1505,1505,1505,1505,1505,15...  1221,1221,1221,1221,1221,1221,1221,1221,1221,1...  7734.0,7734.0,7734.0,7734.0,7734.0,7734.0,7734...  527,527,527,527,527,527,527,527,527,527,527,52...  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...
4           4        5  511956,728354,568450,754044,1011255,741215,362...  302,351,812,1213,142,464,1028,35,1213,351,142,...  3098,3215,641,3736,1483,176,4848,641,3736,4547...  5545.0,5482.0,4265.0,3125.0,4640.0,6662.0,2803...  519,520,520,520,520,520,520,520,520,520,520,52...  3,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,...

In [4]:
all_data_test=all_data_test.drop("Unnamed: 0",axis=1)

In [5]:
all_data_test.head()

   user_id                                          item_path                                           cat_path                                        seller_path                                         brand_path                                    time_stamp_path                                   action_type_path
0        1  181459,779078,779078,452837,543397,504149,5041...  276,276,276,276,276,1023,1023,1023,1023,1252,1...  2245,2245,2245,2245,2245,925,925,925,925,4026,...  4750.0,4750.0,4750.0,4750.0,4750.0,7402.0,7402...  1009,1009,1009,1009,1009,1011,1011,1011,1011,1...  0,0,0,0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,2,2,...
1        2  348983,749563,239288,751744,239288,714176,1972...  177,177,602,602,602,1213,602,602,602,1213,1213...  2223,2223,420,420,420,420,420,420,420,420,420,...  3273.0,3273.0,4953.0,4953.0,4953.0,4058.0,4953...  527,527,626,626,626,626,626,626,626,626,626,62...  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,0,0,...
2        3  895754,895754,182882,182882,985337,175397,9463...  1505,1505,1271,1271,1271,662,1134,1134,1134,45...  795,795,2123,2123,4925,1102,4461,4461,4461,474...  3608.0,3608.0,4796.0,4796.0,8005.0,1214.0,905....  516,516,627,627,627,727,819,819,820,906,906,90...  2,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...
3        4  836727,243874,185489,95474,30073,790055,790055...  612,1577,1505,1505,1505,1505,1505,1505,1505,15...  1221,1221,1221,1221,1221,1221,1221,1221,1221,1...  7734.0,7734.0,7734.0,7734.0,7734.0,7734.0,7734...  527,527,527,527,527,527,527,527,527,527,527,52...  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...
4        5  511956,728354,568450,754044,1011255,741215,362...  302,351,812,1213,142,464,1028,35,1213,351,142,...  3098,3215,641,3736,1483,176,4848,641,3736,4547...  5545.0,5482.0,4265.0,3125.0,4640.0,6662.0,2803...  519,520,520,520,520,520,520,520,520,520,520,52...  3,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,...